/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.CentroCosto;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-07T03:36:42.350Z")

@Api(value = "centroCosto", description = "the centroCosto API")
public interface CentroCostoApi {

    @ApiOperation(value = "adiciona un centro de costos", nickname = "adicionarCentroCosto", notes = "Agregar un centro de costos", tags={ "adminstradores","desarrolladores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Centro de costos adicionado"),
        @ApiResponse(code = 400, message = "Valor de entrada invalido"),
        @ApiResponse(code = 409, message = "Ya existe un centro de costos en el sistema con el mismo identificador") })
    @RequestMapping(value = "/centroCosto/{idCentroCostoParam}:",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> adicionarCentroCosto(@ApiParam(value = "centro de costos a adicionar"  )  @Valid @RequestBody CentroCosto centroCosto);


    @ApiOperation(value = "busca los centros de costo activos", nickname = "buscarCentroCostoById", notes = "Obtiene los centros de costos activos que se encuentren registrados dado un identificador ", response = Object.class, tags={ "desarrolladores","invitados", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado de la consulta de centro de costos  por id.", response = Object.class),
        @ApiResponse(code = 400, message = "Parametro ingresado invalido.") })
    @RequestMapping(value = "/centroCosto/{idCentroCostoParam}:",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> buscarCentroCostoById(@ApiParam(value = "ingrese el id del centro de costos a buscar",required=true) @PathVariable("idCentroCostoParam") String idCentroCostoParam);

}
