/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.UnidadDeNegocio;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-07T03:36:42.350Z")

@Api(value = "unidadNegocio", description = "the unidadNegocio API")
public interface UnidadNegocioApi {

    @ApiOperation(value = "adiciona una unidad de negocio", nickname = "adicionarUnidadNegocio", notes = "Agregar una unidad de negocio", tags={ "adminstradores","desarrolladores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "unidad de negocio adicionada"),
        @ApiResponse(code = 400, message = "Valor de entrada invalido"),
        @ApiResponse(code = 409, message = "Ya existe una unidad de negocio en el sistema con el mismo identificador") })
    @RequestMapping(value = "/unidadNegocio/{idUnidadDeNegocioParam}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> adicionarUnidadNegocio(@ApiParam(value = "unidad de negocio a adicionar"  )  @Valid @RequestBody UnidadDeNegocio unidadNegocio);


    @ApiOperation(value = "busca las unidades de negocio", nickname = "buscarUnidadNegocioById", notes = "Obtiene las unidades de negocio dado un identificador ", response = Object.class, tags={ "desarrolladores","invitados", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resultado de la consulta de unidad de negocio por id.", response = Object.class),
        @ApiResponse(code = 400, message = "Parametro ingresado invalido.") })
    @RequestMapping(value = "/unidadNegocio/{idUnidadDeNegocioParam}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> buscarUnidadNegocioById(@ApiParam(value = "ingrese el id de la unidad de negocio a buscar",required=true) @PathVariable("idUnidadDeNegocioParam") String idUnidadDeNegocioParam);

}
